In [35]:
import numpy as np
import matplotlib.pyplot as plt

from scipy.integrate import odeint
from scipy.sparse import csc_matrix, csr_matrix, coo_matrix
from qutip import *

In [80]:
# functions to calculate parameters

def A(ra, g, gamma):
    return 2 * ra * g**2 / gamma**2

def B(g, gamma, fA):
    return 4 * fA * g**2 / gamma**2

def BdA(g, gamma):
    return 4 * g**2 / gamma**2

def M(n, m, fBdA):
    return 0.5 * (n + m + 2) + (n - m)**2 * fBdA / 8

def N(n, m, fBdA):
    return 0.5 * (n + m + 2) + (n - m)**2 * fBdA / 16

def n_p(fA, fB, kappa):
    return fA * (fA - kappa) / kappa / fB

In [81]:
# parameters

w_c = 2.0 * np.pi
w_a = 2.0 * np.pi
g = 0.1 * 2* np.pi

gamma = 0.01
kappa = 0.01
ra = 0.01

N_max = 5

fA = A(ra, g, gamma)
fB = B(g, gamma, fA)
fBdA = BdA(g, gamma)
aver_n = n_p(fA, fB, kappa)

In [82]:
fA, fB, kappa

(78.95683520871485, 1246836.3652352307, 0.01)

In [83]:
fB/fA, fBdA

(15791.367041742971, 15791.367041742971)

In [84]:
# average photon number for steady state
aver_n

0.4999366742602235

In [85]:
# coefficients of the differential equation

def fnm(n, m, fA, fBdA, kappa):
    return - (M(n, m, fBdA) * fA / (1 + N(n, m, fBdA) * fBdA)) - 0.5 * kappa * (n + m)

def gnm(n, m, fA, fBdA):
    return np.sqrt(n * m) * fA / (1 + N (n, m, fBdA) * fBdA)

def hnm(n, m, kappa):
    return kappa * np.sqrt((n + 1) * (m + 1))

In [86]:
# parameters in the differential equation
ij = range(N_max)
FNM = np.array([fnm(i, j, fA, fBdA, kappa) for i in ij for j in ij]).reshape(N_max, N_max)
GNM = np.array([gnm(i, j, fA, fBdA) for i in ij for j in ij]).reshape(N_max, N_max)
HNM = np.array([hnm(i, j, kappa) for i in ij for j in ij]).reshape(N_max, N_max)

In [94]:
FNM

array([[-0.00499968, -0.01499241, -0.01999747, -0.02499859, -0.02999905],
       [-0.01499241, -0.01499984, -0.02498737, -0.0299962 , -0.03499803],
       [-0.01999747, -0.02498737, -0.02499989, -0.03498233, -0.03999494],
       [-0.02499859, -0.0299962 , -0.03498233, -0.03499992, -0.04497731],
       [-0.02999905, -0.03499803, -0.03999494, -0.04497731, -0.04499994]])

In [93]:
FNM.reshape(-1)

array([-0.00499968, -0.01499241, -0.01999747, -0.02499859, -0.02999905,
       -0.01499241, -0.01499984, -0.02498737, -0.0299962 , -0.03499803,
       -0.01999747, -0.02498737, -0.02499989, -0.03498233, -0.03999494,
       -0.02499859, -0.0299962 , -0.03498233, -0.03499992, -0.04497731,
       -0.02999905, -0.03499803, -0.03999494, -0.04497731, -0.04499994])

In [ ]:
# differential equation
def rho_nm_dot(rho_nm, t):
    rho = rho_nm.reshape(N_max, N_max)
    rho_new = np.zeros([N_max, N_max])
    
    ij = range(N_max)
    for i in ij:
        for j in ij:
            rho_new[i, j] = np.sum()

In [101]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])